ALTER TABLE courses ADD COLUMN IF NOT EXISTS video_url VARCHAR(255);
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS video_url VARCHAR(255);
ALTER TABLE courses ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'draft';
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'draft';
